development:
  adapter: postgresql
  encoding: unicode
  database: development_topiclinks
  host: localhost
  pool: 5
  username: luis
  password: rodge24

test:
  adapter: postgresql
  encoding: unicode
  database: test_topiclinks
  host: localhost
  pool: 5
  username: luis
  password: rodge24

production:
  adapter: postgresql
  encoding: unicode
  database: production_topiclinks
  host: localhost
  pool: 5
  username: luis
  password: rodge24